import os
from dotenv import load_dotenv

load_dotenv()

# Server Configuration
PORT = int(os.getenv('PORT', 3000))
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

# WATI API Configuration
WATI_API_URL = os.getenv('WATI_API_URL')
WATI_TOKEN = os.getenv('WATI_TOKEN')
WATI_PHONE_ID = os.getenv('WATI_PHONE_ID')
WATI_WEBHOOK_TOKEN = os.getenv('WATI_WEBHOOK_TOKEN')

# MongoDB Configuration
MONGO_URI = os.getenv('MONGO_URI')
MONGO_DB_NAME = 'ot_generator'

# Azure OpenAI Configuration
AZURE_OPENAI_ENDPOINT = os.getenv('AZURE_OPENAI_ENDPOINT')
AZURE_OPENAI_API_KEY = os.getenv('AZURE_OPENAI_API_KEY')
AZURE_OPENAI_WHISPER_DEPLOYMENT = os.getenv('AZURE_OPENAI_WHISPER_DEPLOYMENT')
AZURE_OPENAI_WHISPER_API_KEY = os.getenv('AZURE_OPENAI_WHISPER_API_KEY')

# Chilexpress API Configuration
CHILEXPRESS_API_KEY = os.getenv('CHILEXPRESS_API_KEY')
CHILEXPRESS_API_VERSION = 'v4'
CHILEXPRESS_BASE_URL = f'https://devservices.wschilexpress.com/agendadigital/api/{CHILEXPRESS_API_VERSION}'
CHILEXPRESS_GEO_BASE_URL = 'https://devservices.wschilexpress.com/georeference/v2.1/api/v2.0'

# Application State
STATES = {
    'IDLE': 'IDLE',
    'GATHERING_QUOTE_DATA': 'GATHERING_QUOTE_DATA',
    'CONFIRMING_QUOTE_DATA': 'CONFIRMING_QUOTE_DATA',
    'QUOTATION_RESULTS_SHOWN': 'QUOTATION_RESULTS_SHOWN',
    'GATHERING_SENDER_DATA': 'GATHERING_SENDER_DATA',
    'CONFIRMING_SENDER_DATA': 'CONFIRMING_SENDER_DATA',
    'GATHERING_RECIPIENT_DATA': 'GATHERING_RECIPIENT_DATA',
    'CONFIRMING_RECIPIENT_DATA': 'CONFIRMING_RECIPIENT_DATA',
    'CHOOSING_DELIVERY_TYPE': 'CHOOSING_DELIVERY_TYPE',
    'GETTING_DELIVERY_ADDRESS': 'GETTING_DELIVERY_ADDRESS',
    'SELECTING_OFFICE': 'SELECTING_OFFICE',
    'CONFIRMING_DELIVERY_DETAILS': 'CONFIRMING_DELIVERY_DETAILS',
    'AWAITING_PAYMENT_METHOD': 'AWAITING_PAYMENT_METHOD',
    'FINAL_CONFIRMATION': 'FINAL_CONFIRMATION',
    'OT_GENERATED': 'OT_GENERATED'
}

# Logging
LOG_DIR = 'logs'
WEBHOOK_LOG_FILE = 'webhook_events.log'
